spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/peluqueria
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

spring.thymeleaf.check-template-location=false

# App Properties
bezkoder.app.jwtSecret=U8xvB7rT9qL2eY6mN3zP1wK4aJ5tH8oC0fR6gD7uV9xL2bN3qT4rW5yZ6aB7cD8X
bezkoder.app.jwtExpirationMs=360000000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=albadelpino1@gmail.com
# Asegúrate de que estos 16 caracteres sean tu Contraseña de Aplicación de Google actual activa
spring.mail.password=slztsudeethdpdjm

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# CORRECCIÓN DE LOS ERRORES DE TLS/SSL:
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

# Recomendado: Tiempos de espera para que no se quede colgada la app si falla
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000